name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Restore workspace cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            example/node_modules
          key: dependencies-${{ runner.os }}-${{ hashFiles('package.json') }}
          restore-keys: |
            dependencies-${{ runner.os }}-

      - name: Install dependencies (example)
        run: yarn install --cwd example --frozen-lockfile

      - name: Install dependencies (root)
        run: yarn install --frozen-lockfile

      - name: Save workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: .

  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run lint
        run: yarn lint

  typescript:
    runs-on: ubuntu-latest
    needs: install-dependencies
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Typecheck files
        run: yarn typescript

#  unit-tests:
#     runs-on: ubuntu-latest
#     needs: install-dependencies
#     strategy:
#       matrix:
#         node-version: [18.x]

#     steps:
#       - name: Download workspace
#         uses: actions/download-artifact@v4
#         with:
#           name: workspace
#           path: .

#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ matrix.node-version }}

#       - name: Run unit tests
#         run: yarn test --coverage

#       - name: Upload coverage
#         uses: actions/upload-artifact@v4
#         with:
#           name: coverage
#           path: coverage

  build-package:
    runs-on: ubuntu-latest
    needs: install-dependencies
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build package
        run: yarn prepare